import { IndustryDNA } from "./types";

export const INDUSTRIES_DATA: IndustryDNA[] = [
  {
    id: "tech",
    name: "Công nghệ & Trí tuệ nhân tạo (AI)",
    slug: "cong-nghe-ai",
    icon: "💻",
    color: "from-blue-500 to-indigo-600",
    tagline: "Kiến tạo hạ tầng số, phần mềm thông minh và giải pháp tự động hóa thế hệ mới",
    description: "Lĩnh vực cốt lõi thúc đẩy chuyển đổi số toàn cầu, kết hợp khoa học máy tính, kỹ thuật phần mềm, dữ liệu lớn và AI để giải quyết các bài toán phức tạp.",
    traits: ["Tốc độ biến đổi công nghệ cực nhanh", "Đòi hỏi khả năng tự học liên tục", "Môi trường làm việc linh hoạt, toàn cầu"],
    typical_roles: ["Software Engineer", "Data Scientist / AI Engineer", "Product Manager", "DevOps Cloud Engineer", "Cybersecurity Specialist"],
    emerging_trends: ["Generative AI & Agentic Workflows", "Edge Computing & IoT", "Bảo mật Zero-Trust", "Điện toán đám mây tích hợp"],
    ai_impact_overview: "AI vừa là sản phẩm vừa là công cụ; tự động hóa việc viết mã căn bản nhưng nâng cao nhu cầu về kiến trúc sư giải pháp và tư duy hệ thống."
  },
  {
    id: "engineering",
    name: "Kỹ thuật, Cơ điện tử & Tự động hoá",
    slug: "ky-thuat-tu-dong-hoa",
    icon: "⚙️",
    color: "from-amber-500 to-orange-600",
    tagline: "Hiện thực hoá các cỗ máy thông minh, robot công nghiệp và chuỗi cung ứng vật lý",
    description: "Giao thoa giữa cơ khí, điện tử, viễn thông và robot nhằm xây dựng thế giới vật lý an toàn, tiện nghi và hiệu suất cao.",
    traits: ["Đề cao tính chính xác và an toàn kỹ thuật", "Tư duy không gian và giải quyết vấn đề vật lý", "Kết hợp giữa thiết kế mô phỏng và vận hành thực tế"],
    typical_roles: ["Kỹ sư Cơ điện tử / Robotics", "Kỹ sư Vi mạch Bán dẫn", "Kỹ sư Điện - Tự động hóa", "Kỹ sư Xây dựng & Kết cấu", "Kỹ sư Logistics"],
    emerging_trends: ["Công nghiệp bán dẫn và đóng gói chip", "Nhà máy thông minh (Smart Factory)", "Năng lượng tái tạo và lưới điện thông minh"],
    ai_impact_overview: "AI được nhúng vào PLC và hệ thống điều khiển tự động (Edge AI), nâng cao năng suất bảo trì dự đoán và kiểm tra khuyết tật."
  },
  {
    id: "business",
    name: "Kinh doanh, Thương mại & Quản trị",
    slug: "kinh-doanh-quan-tri",
    icon: "📈",
    color: "from-emerald-500 to-teal-600",
    tagline: "Vận hành tổ chức, mở rộng thị trường và tối ưu mô hình kinh doanh",
    description: "Tập trung vào chiến lược phát triển, quản lý chuỗi cung ứng, thương mại quốc tế và khởi nghiệp sáng tạo.",
    traits: ["Đòi hỏi nhạy bén thương mại và tư duy chiến lược", "Giao tiếp, thuyết phục và lãnh đạo đội ngũ", "Thích ứng cao với biến động thị trường"],
    typical_roles: ["Business Development Manager", "Chuyên viên Quản trị Chuỗi cung ứng", "Chuyên viên Thương mại Điện tử", "Tư vấn Quản trị Chiến lược", "Nhà sáng lập Startup"],
    emerging_trends: ["Kinh doanh đa kênh (Omnichannel)", "Chuỗi cung ứng xanh và bền vững (ESG)", "Dữ liệu phục vụ ra quyết định kinh doanh"],
    ai_impact_overview: "AI hỗ trợ dự báo nhu cầu thị trường, phân tích hành vi khách hàng và tối ưu hóa vận hành, giúp nhà quản trị tập trung vào chiến lược."
  },
  {
    id: "finance",
    name: "Tài chính, Ngân hàng & Fintech",
    slug: "tai-chinh-fintech",
    icon: "🏦",
    color: "from-cyan-500 to-blue-600",
    tagline: "Điều phối dòng vốn, quản trị rủi ro và phát triển công nghệ tài chính",
    description: "Đảm bảo huyết mạch dòng tiền cho nền kinh tế thông qua phân tích đầu tư, thẩm định tín dụng, quản lý tài sản và ví điện tử.",
    traits: ["Tư duy định lượng và độ nhạy số liệu", "Tính kỷ luật, bảo mật và tuân thủ đạo đức nghề nghiệp", "Thu nhập và cơ hội thăng tiến tỷ lệ thuận với năng lực"],
    typical_roles: ["Chuyên viên Phân tích Đầu tư (Equity Analyst)", "Chuyên viên Quản trị Rủi ro Tài chính", "Product Manager Fintech", "Chuyên viên Ngân hàng Doanh nghiệp", "Kiểm toán viên (CPA/ACCA)"],
    emerging_trends: ["Tài chính phi tập trung và Open Banking", "Tự động hóa thanh toán bằng AI", "Đầu tư bền vững & Tiêu chuẩn ESG"],
    ai_impact_overview: "AI chấm điểm tín dụng tự động và phát hiện gian lận tức thì; vai trò phân tích tài chính chuyển dịch sang tư vấn chiến lược dòng vốn."
  },
  {
    id: "healthcare",
    name: "Y tế, Dược phẩm & Công nghệ Sinh học",
    slug: "y-te-duoc-sinh-hoc",
    icon: "🩺",
    color: "from-rose-500 to-red-600",
    tagline: "Chăm sóc sức khỏe con người, nghiên cứu gen và y học cá thể hóa",
    description: "Một trong những lĩnh vực cao quý và ổn định nhất, từ chẩn đoán điều trị lâm sàng đến công nghệ sinh học và quản lý y tế cộng đồng.",
    traits: ["Trách nhiệm đạo đức và tính cẩn trọng tuyệt đối", "Thời gian đào tạo dài và đòi hỏi sự kiên trì bền bỉ", "Lòng trắc ẩn và kỹ năng thấu cảm với bệnh nhân"],
    typical_roles: ["Bác sĩ Đa khoa / Chuyên khoa", "Dược sĩ Lâm sàng / R&D Dược", "Kỹ sư Y sinh (Biomedical)", "Chuyên gia Dữ liệu Y tế (Bioinformatics)", "Điều dưỡng trưởng"],
    emerging_trends: ["Chẩn đoán hình ảnh y khoa bằng AI", "Y học cá thể hóa dựa trên giải mã gen", "Telemedicine và thiết bị theo dõi sinh hiệu liên tục"],
    ai_impact_overview: "AI hỗ trợ đọc phim X-quang, MRI và sàng lọc phân tử thuốc; chuyên môn khám bệnh và chăm sóc trực tiếp của y bác sĩ không thể bị thay thế."
  },
  {
    id: "creative",
    name: "Thiết kế, Nghệ thuật & Sáng tạo Số",
    slug: "thiet-ke-sang-tao-so",
    icon: "🎨",
    color: "from-pink-500 to-rose-600",
    tagline: "Tạo dựng trải nghiệm thị giác, giao diện số và tác phẩm chạm đến cảm xúc",
    description: "Bao gồm thiết kế đồ họa, UI/UX sản phẩm số, hoạt hình 3D, thiết kế thời trang và kiến trúc nội thất.",
    traits: ["Tư duy thẩm mỹ và cảm quan màu sắc, bố cục", "Khả năng đồng cảm với người dùng cuối", "Thích tự do khám phá và tạo ra cái mới"],
    typical_roles: ["UI/UX Product Designer", "3D Animator / Motion Designer", "Giám đốc Nghệ thuật (Art Director)", "Game Designer", "Nhà thiết kế Đồ họa Thương hiệu"],
    emerging_trends: ["Thiết kế trải nghiệm không gian (Spatial Computing)", "Tạo hình và dựng cảnh hỗ trợ bởi Generative AI", "Micro-interactions và thiết kế tương tác tinh gọn"],
    ai_impact_overview: "AI thay đổi cách phác thảo concept nhanh gấp 10 lần, trao quyền cho người làm sáng tạo trở thành đạo diễn nghệ thuật tổng thể."
  },
  {
    id: "communication",
    name: "Truyền thông, Marketing & Nội dung số",
    slug: "truyen-thong-marketing",
    icon: "📢",
    color: "from-purple-500 to-violet-600",
    tagline: "Kể câu chuyện thương hiệu, kết nối cộng đồng và truyền cảm hứng hành động",
    description: "Nắm bắt tâm lý công chúng, xây dựng chiến dịch tiếp thị đa kênh, quản trị thương hiệu và quan hệ báo chí.",
    traits: ["Khả năng ngôn ngữ và kể chuyện hấp dẫn", "Tư duy sáng tạo kết hợp đo lường dữ liệu chuyển đổi", "Tương tác con người và làm việc nhóm tích cực"],
    typical_roles: ["Digital Marketing Strategist", "Brand Manager", "Chuyên viên Quan hệ Công chúng (PR)", "Content Creator / Copywriter", "Community Lead"],
    emerging_trends: ["Video ngắn và tiếp thị dựa trên người sáng tạo", "Cá nhân hóa nội dung theo hành trình người dùng", "Truyền thông dựa trên dữ liệu (Data-driven PR)"],
    ai_impact_overview: "AI hỗ trợ tạo nháp bài viết và phân tích sentiment mạng xã hội; chiều sâu văn hóa và cảm xúc chạm trái tim vẫn là lợi thế vượt trội của con người."
  },
  {
    id: "education",
    name: "Giáo dục, Đào tạo & Khai vấn",
    slug: "giao-duc-khai-van",
    icon: "🎓",
    color: "from-indigo-500 to-sky-600",
    tagline: "Phát triển tiềm năng con người, lan tỏa tri thức và công nghệ học tập",
    description: "Giảng dạy học đường, phát triển chương trình đào tạo doanh nghiệp (L&D), tư vấn hướng nghiệp và ứng dụng EdTech.",
    traits: ["Lòng kiên nhẫn, thấu hiểu và truyền cảm hứng", "Khả năng cấu trúc thông tin phức tạp thành dễ hiểu", "Coi trọng giá trị phụng sự xã hội và phát triển con người"],
    typical_roles: ["Giảng viên / Giáo viên chuyên môn", "Chuyên gia Đào tạo Doanh nghiệp (L&D)", "Chuyên gia Thiết kế Trải nghiệm Học tập (Instructional Designer)", "Khai vấn Nghề nghiệp (Career Coach)", "Chuyên viên Phát triển Nội dung EdTech"],
    emerging_trends: ["Học tập thích ứng cá nhân hóa (Adaptive Learning)", "Microlearning và gamification trong học tập", "Đào tạo kỹ năng làm việc cùng AI"],
    ai_impact_overview: "AI giúp soạn giáo án và chấm điểm nhanh; giáo viên chuyển thành người cố vấn, khích lệ và rèn luyện tư duy phản biện cho người học."
  },
  {
    id: "law",
    name: "Luật pháp, Chính sách & Quan hệ Quốc tế",
    slug: "luat-chinh-sach",
    icon: "⚖️",
    color: "from-slate-600 to-zinc-700",
    tagline: "Bảo vệ công lý, định hình hành lang pháp lý và điều phối quan hệ ngoại giao",
    description: "Tư vấn luật doanh nghiệp, tranh tụng, xây dựng văn bản quy phạm, thương lượng hiệp định quốc tế và sở hữu trí tuệ.",
    traits: ["Tư duy logic phản biện và lập luận sắc bén", "Trí nhớ tốt, đọc hiểu văn bản quy phạm chuyên sâu", "Liêm chính và tôn trọng chuẩn mực đạo đức pháp lý"],
    typical_roles: ["Luật sư Tranh tụng / Tư vấn Doanh nghiệp", "Chuyên viên Pháp chế (In-house Legal Counsel)", "Chuyên gia Sở hữu Trí tuệ (IP)", "Chuyên viên Ngoại giao & Hợp tác Quốc tế", "Công chứng viên / Thẩm phán"],
    emerging_trends: ["LegalTech tra cứu văn bản pháp luật bằng AI", "Khung pháp lý về AI, dữ liệu cá nhân và an ninh mạng", "Luật thương mại điện tử và chuỗi cung ứng xuyên biên giới"],
    ai_impact_overview: "AI xử lý việc rà soát hợp đồng và tìm tiền lệ án; kỹ năng đàm phán, tranh luận trước tòa và đạo lý pháp đình thuộc về con người."
  },
  {
    id: "science",
    name: "Khoa học Tự nhiên & Nghiên cứu Cơ bản",
    slug: "khoa-hoc-tu-nhien",
    icon: "🔬",
    color: "from-teal-500 to-emerald-600",
    tagline: "Khám phá quy luật tự nhiên, vật liệu tiên tiến và nền tảng tri thức nhân loại",
    description: "Toán học, Vật lý học, Hóa học, Sinh học phân tử và Khoa học môi trường; cái nôi của mọi phát minh công nghệ.",
    traits: ["Niềm đam mê tìm hiểu bản chất và đặt câu hỏi 'Tại sao'", "Tư duy trừu tượng và suy luận logic chặt chẽ", "Kiên nhẫn theo đuổi các nghiên cứu dài hạn"],
    typical_roles: ["Nhà Nghiên cứu Khoa học (Researcher)", "Chuyên gia Phân tích Dữ liệu Khoa học", "Chuyên gia Hóa học Phân tích / Vật liệu mới", "Chuyên gia Sinh thái học", "Giảng viên Đại học"],
    emerging_trends: ["AI for Science (dự đoán cấu trúc protein, mô phỏng vật liệu)", "Khoa học khí hậu và mô hình hóa thời tiết", "Toán ứng dụng trong mã hóa lượng tử"],
    ai_impact_overview: "AI trở thành siêu trợ lý cho các nhà khoa học, giúp sàng lọc giả thuyết và tăng tốc nghiên cứu từ vài năm xuống vài tuần."
  },
  {
    id: "environment",
    name: "Môi trường, Nông nghiệp Công nghệ cao & Bền vững",
    slug: "moi-truong-nong-nghiep-xanh",
    icon: "🌱",
    color: "from-green-600 to-emerald-700",
    tagline: "Bảo vệ hệ sinh thái, an ninh lương thực và chuyển dịch kinh tế tuần hoàn",
    description: "Ứng dụng công nghệ cao vào nuôi trồng, quản trị tài nguyên nước, xử lý rác thải và tín chỉ carbon.",
    traits: ["Gắn bó với tự nhiên và sự sống", "Tư duy hệ sinh thái và giải pháp phát triển bền vững", "Chấp nhận làm việc thực địa kết hợp phòng thí nghiệm"],
    typical_roles: ["Kỹ sư Nông nghiệp Thông minh (Smart Agriculture)", "Chuyên gia Đánh giá Tác động Môi trường (EIA)", "Chuyên gia Kiểm kê Khí nhà kính & Tín chỉ Carbon", "Kỹ sư Quản lý Tài nguyên Nước", "Nhà quản lý Dự án Xanh"],
    emerging_trends: ["Nông nghiệp chính xác dùng Drone & IoT", "Kinh tế tuần hoàn và tái chế sinh học", "Thị trường tín chỉ carbon quốc tế"],
    ai_impact_overview: "AI dự báo dịch bệnh mùa màng, tối ưu phân bón tưới tiêu và giám sát biến đổi độ che phủ rừng bằng ảnh vệ tinh."
  },
  {
    id: "hospitality",
    name: "Du lịch, Khách sạn & Quản trị Trải nghiệm",
    slug: "du-lich-khach-san",
    icon: "✈️",
    color: "from-orange-500 to-amber-600",
    tagline: "Đón tiếp nồng hậu, quản lý chuỗi dịch vụ cao cấp và kết nối văn hóa",
    description: "Quản lý khách sạn, resort, tổ chức sự kiện quốc tế, hàng không và phát triển điểm đến du lịch bền vững.",
    traits: ["Kỹ năng giao tiếp và ứng xử tinh tế", "Chỉ số cảm xúc (EQ) cao, yêu thích dịch vụ khách hàng", "Khả năng ứng biến linh hoạt trong tình huống bất ngờ"],
    typical_roles: ["Quản lý Khách sạn / Resort (General Manager)", "Chuyên gia Tổ chức Sự kiện / MICE", "Quản lý Trải nghiệm Khách hàng (Customer Experience)", "Chuyên gia Phát triển Tour Văn hóa", "Chuyên viên Hàng không"],
    emerging_trends: ["Du lịch sinh thái và trải nghiệm văn hóa bản địa", "Ứng dụng công nghệ check-in tự động và khách sạn thông minh", "Tổ chức sự kiện kết hợp (Hybrid Events)"],
    ai_impact_overview: "AI xử lý đặt phòng và phản hồi tự động 24/7; sự chân thành, ấm áp và tinh tế trong nụ cười tiếp đón là điều công nghệ không thể có."
  }
];
